# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: [x64, arm64, ia32]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: build rev822
      run: npm run build -- --${{ matrix.arch }}
    - name: upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: rev822-${{ matrix.os }}-${{ matrix.arch }}.zip
        path: out/rev822.zip
        retention-days: 90
